repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        files: ^services/notification/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^services/notification/

-   repo: local
    hooks:
    -   id: golangci-lint
        name: golangci-lint
        language: system
        entry: make lint-go
        types: [go]
        pass_filenames: false
