name: 'Setup Go with dependencies'
description: 'Setup Go and install common dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: go.work
        cache: true
    - name: Install jq
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi
    - name: Install golangci-lint
      shell: bash
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
    - name: Install govulncheck
      shell: bash
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
