name: 'Setup Go with dependencies'
description: 'Setup Go and install common dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: go.work
        cache: false
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install golang.org/x/vuln/cmd/govulncheck@latest
